site_name: Lab Manual - Humphries Lab
site_url: https://Humphries-Lab.github.io/Lab-Manual
edit_uri: https://github.com/Humphries-Lab/Lab-Manual/edit/main/content
docs_dir: content
nav:
    - Introduction: index.md
    - practical.md
    - roles.md
    - principles.md
    - policies.md
    - collaborators.md
    - funders.md
    - reading.md

# The following is not really the copyright notice.
# It's rather a ± hack to get custom text in the footer.
# The 'spans' are to have the spaces inside be non-breaking.
# (see `content/style/custom.css`)
copyright: >
    <span>Mark Humphries</span> ·
    <span>University of Nottingham</span> ·
    <span>29th March 2019</span> ·
    Correspondence:
    <a href="mailto:mark.humphries@nottingham.ac.uk">
    mark.humphries@nottingham.ac.uk</a>

theme:
    name: material
    features:
        - navigation.footer
        - content.action.edit

extra_css:
  - style/custom.css

extra:
    # Remove the "Made with Material for MkDocs" link
    # (they can read that in the repo)
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Humphries-Lab/Lab-Manual
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/markdhumphries

plugins:
    - search
    - git-revision-date-localized:
        enable_creation_date: false

markdown_extensions:
    - toc:
        permalink: '#'

    # This enables the `!!! note` sidebars
    - admonition

    # https://python-markdown.github.io/extensions/smarty/
    # "x" → “x”, -- → –, etc
    - smarty
