site_name: Lab Manual - Humphries Lab
site_url: https://humphries-lab.github.io/Lab-Manual
edit_uri: https://github.com/Humphries-Lab/Lab-Manual/edit/main/content
docs_dir: content  # Default: docs
nav:
    - Introduction: index.md
    - practical.md
    - roles.md
    - principles.md
    - policies.md
    - collaborators.md
    - funders.md
    - reading.md

# The following is not really the copyright notice.
# It's rather a sort-of hack to get custom text in the footer.
# The 'spans' are to have the spaces inside be non-breaking -- i.e. so that
# the text inside stays on one line; this is mostly relevant on mobile.
# (The non-breaking ('nowrap') rule is defined in `content/style/custom.css`)
copyright: >
    <span>Mark Humphries</span> ·

    <span>University of Nottingham</span> ·

    <span>29th March 2019</span> ·

    Correspondence:
    <a href="mailto:mark.humphries@nottingham.ac.uk">
    mark.humphries@nottingham.ac.uk</a>

theme:
    name: material

    features:
        - navigation.footer    # next/prev page in footer
        - content.action.edit  # Icon link next to H1, to edit on GH

    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              name: Switch to dark mode
              icon: material/brightness-7
          primary: teal
          accent: teal

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              name: Switch to light mode
              icon: material/brightness-4
          primary: teal
          accent: teal

extra_css:
  - style/custom.css

extra:

    # Remove the "Made with Material for MkDocs" link
    # (they can read that in the repo)
    generator: false

    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Humphries-Lab/Lab-Manual

        - icon: fontawesome/brands/twitter
          link: https://twitter.com/markdhumphries

        - icon: fontawesome/solid/house
          link: https://www.humphries-lab.org/



plugins:
    - search
    - git-revision-date-localized

markdown_extensions:

    # Makes (sub)headings linkable
    - toc:
        permalink: '#'

    # This enables the `!!! note` sidebars
    - admonition

    # Auto-converts "x" → “x”, -- → –, etc
    # (https://python-markdown.github.io/extensions/smarty)
    - smarty
